### ISSUE TITLE
app crashing after first start

### ISSUE THREAD

**Issue by tshirtman** [bither/bither-android#36]
Installed the app yesterday, was working well at that point.

Restarting it today, it stops right after displaying the splashscreen, sometime several time in a row.

I used adb to look at the log, and the error is the following (usually multiple times in a row).
```
I/MultiDex( 9066): VM has multidex support, MultiDex support library is disabled.
E/Vold    (  321): Failed to find mounted volume for /storage/sdcard1/Android/data/net.bither/cache/
W/Vold    (  321): Returning OperationFailed - no handler for errno 0
W/ContextImpl( 9066): Failed to ensure directory: /storage/sdcard1/Android/data/net.bither/cache
E/Vold    (  321): Failed to find mounted volume for /storage/sdcard1/Android/data/net.bither/cache/
W/Vold    (  321): Returning OperationFailed - no handler for errno 0
W/ContextImpl( 9066): Failed to ensure directory: /storage/sdcard1/Android/data/net.bither/cache
E/UEHandler( 9066): java.lang.ExceptionInInitializerError
E/UEHandler( 9066): 	at net.bither.BitherApplication$1.run(BitherApplication.java:187)
E/UEHandler( 9066): 	at java.lang.Thread.run(Thread.java:818)
E/UEHandler( 9066): Caused by: java.lang.NullPointerException: Attempt to get length of null array
E/UEHandler( 9066): 	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
E/UEHandler( 9066): 	at net.bither.bitherj.e.a.a(Script.java:186)
E/UEHandler( 9066): 	at net.bither.bitherj.e.a.<init>(Script.java:107)
E/UEHandler( 9066): 	at net.bither.bitherj.core.Out.f(Out.java:160)
E/UEHandler( 9066): 	at net.bither.bitherj.core.a.z(Address.java:171)
E/UEHandler( 9066): 	at net.bither.bitherj.core.a.d(Address.java:140)
E/UEHandler( 9066): 	at net.bither.bitherj.core.a.<init>(Address.java:85)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.a.c(AbstractAddressProvider.java:968)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.a.b(AbstractAddressProvider.java:42)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:709)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:703)
E/UEHandler( 9066): 	at net.bither.d.a.b.b(AndroidDb.java:71)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.f.b(AbstractProvider.java:38)
E/UEHandler( 9066): 	at net.bither.bitherj.a.a.a.e(AbstractAddressProvider.java:703)
E/UEHandler( 9066): 	at net.bither.bitherj.core.b.z(AddressManager.java:119)
E/UEHandler( 9066): 	at net.bither.bitherj.core.b.<init>(AddressManager.java:57)
E/UEHandler( 9066): 	at net.bither.bitherj.core.b.<clinit>(AddressManager.java:43)
```

I did check and the folder in /storage/sdcard1/… is there. I moved it aside in case, and restarded, it was recreated and now contains:

```
cache:
    ad
    bither
        error.log
```

`cache/bither/error.log` contains another copy of the error

```
java.lang.ExceptionInInitializerError
	at net.bither.BitherApplication$1.run(BitherApplication.java:187)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
	at net.bither.bitherj.e.a.a(Script.java:186)
	at net.bither.bitherj.e.a.<init>(Script.java:107)
	at net.bither.bitherj.core.Out.f(Out.java:160)
	at net.bither.bitherj.core.a.z(Address.java:171)
	at net.bither.bitherj.core.a.d(Address.java:140)
	at net.bither.bitherj.core.a.<init>(Address.java:85)
	at net.bither.bitherj.a.a.a.c(AbstractAddressProvider.java:968)
	at net.bither.bitherj.a.a.a.b(AbstractAddressProvider.java:42)
	at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:709)
	at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:703)
	at net.bither.d.a.b.b(AndroidDb.java:71)
	at net.bither.bitherj.a.a.f.b(AbstractProvider.java:38)
	at net.bither.bitherj.a.a.a.e(AbstractAddressProvider.java:703)
	at net.bither.bitherj.core.b.z(AddressManager.java:119)
	at net.bither.bitherj.core.b.<init>(AddressManager.java:57)
	at net.bither.bitherj.core.b.<clinit>(AddressManager.java:43)
	... 2 more
```

Anything i can do to fix it?

**Comment by tshirtman** [comment]
I see a commit (52ec507fa98a21996b1f365d18608656d496314d) was done since last release to fix a crash with bitcoin diamond (?) it could well be related, since i did install bither to claim bitcoin diamonds.

**Comment by tshirtman** [comment]
I reinstalled the app and was able to claim other coins, it didn't crash anymore, weird.

**Comment by bithernet** [comment]
We will look into this, thanks for your feedback.
