### ISSUE TITLE
求助，从coinbase转了一笔比特币后钱包打不开了！

### ISSUE THREAD

**Issue by autnullsu** [bither/bither-android#49]
今天从coinbase转了一笔比特币到bither钱包后，钱包就打不开了。
错误信息如下：
`03-05 13:38:45.686 14275-14303/? E/UEHandler: java.lang.ExceptionInInitializerError
at net.bither.bitherj.core.b.a(AddressManager.java:69)
at net.bither.BitherApplication$1.run(BitherApplication.java:187)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
at net.bither.bitherj.e.a.a(Script.java:186)
at net.bither.bitherj.e.a.<init>(Script.java:107)
at net.bither.bitherj.core.Out.f(Out.java:160)
at net.bither.bitherj.core.a.A(Address.java:172)
at net.bither.bitherj.core.a.d(Address.java:141)
at net.bither.bitherj.core.a.<init>(Address.java:86)
at net.bither.bitherj.a.a.a.c(AbstractAddressProvider.java:968)
at net.bither.bitherj.a.a.a.b(AbstractAddressProvider.java:42)
at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:709)
at net.bither.bitherj.a.a.a$17.a(AbstractAddressProvider.java:703)
at net.bither.d.a.b.b(AndroidDb.java:71)
at net.bither.bitherj.a.a.f.b(AbstractProvider.java:38)
at net.bither.bitherj.a.a.a.e(AbstractAddressProvider.java:703)
at net.bither.bitherj.core.b.z(AddressManager.java:119)
at net.bither.bitherj.core.b.<init>(AddressManager.java:57)
at net.bither.bitherj.core.b.<clinit>(AddressManager.java:43)
at net.bither.bitherj.core.b.a(AddressManager.java:69) 
at net.bither.BitherApplication$1.run(BitherApplication.java:187) 
at java.lang.Thread.run(Thread.java:761) `

另外，看了下这笔转账的transaction，发现输入和输出中有些比特币地址是bc1开头的，烦请帮助解决。

**Comment by autnullsu** [comment]
<img width="1218" alt="wx20180305-143626 2x" src="https://user-images.githubusercontent.com/696700/36960597-a6368156-2082-11e8-9610-e8114e230956.png">

**Comment by autnullsu** [comment]
上图中不显示地址的输入输出，是bc1开头的比特币地址。
也不知道猴年马月才能解决这个问题，比特币都在手机上也打不开，私钥也没备份出来。
项目很久也不更新了，看来只能寄希望于将来手机能root了。

**Comment by wangyaopd** [comment]
您好 请您留下邮箱 或加我微信：siriusjs51 请放心 后续我们会跟进为您解决此事

**Comment by zhenHH** [comment]
@autnullsu 请更新到1.8.4，该问题已修复。
